spring.application.name=backend
server.port=8181

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/escaping_the_fog
spring.datasource.username=postgres
spring.datasource.password=bondstone

# Hibernate (JPA) settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
